modName = JEI Copy ID
modId = jeicopyid
modGroup = com.jeicopyid
includeMCVersionJar = false
autoUpdateBuildScript = false
minecraftVersion = 1.12.2
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = true
apiPackage =
accessTransformersFile =
usesMixins = false
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
modArchivesBaseName = jei-copy-id
modVersion = 1.0.0
generateGradleTokenClass =
gradleTokenModId =
gradleTokenModName =
gradleTokenVersion =
useSrcApiPath = false
includeWellKnownRepositories = true
includeCommonDevEnvMods = false
stripForgeRequirements = false
noPublishedSources = true
mixinProviderSpec = zone.rong:mixinbooter:10.6
forceEnableMixins = false
mixinConfigRefmap = mixins.jeicopyid.refmap.json
enableCoreModDebug = false
generateMixinConfig = true
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
separateRunDirectories = false
versionDisplayFormat = $MOD_NAME - $VERSION
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
releaseType = release
generateDefaultChangelog = false
customMavenPublishUrl =
mavenArtifactGroup = com.jeicopyid
enableSpotless = false
enableJUnit = false
deploymentDebug = false
enableJava17RunTasks = true
additionalJavaArguments =